# Generated by Django 3.2.13 on 2022-06-08 02:32

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CollectorErrataProduct",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("et_id", models.IntegerField(unique=True)),
                ("name", models.TextField(unique=True)),
                ("short_name", models.TextField(unique=True)),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectorErrataProductVersion",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("et_id", models.IntegerField(unique=True)),
                ("name", models.TextField(unique=True)),
                (
                    "brew_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024), default=list, size=None
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="collectors.collectorerrataproduct",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectorErrataProductVariant",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("et_id", models.IntegerField(unique=True)),
                ("name", models.TextField(unique=True)),
                ("cpe", models.TextField(null=True)),  # noqa: DJ01
                (
                    "product_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="collectors.collectorerrataproductversion",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
