# Generated by Django 3.2.15 on 2022-09-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectorComposeRhelModule",
            fields=[
                ("build_id", models.IntegerField(primary_key=True, serialize=False)),
                ("nvr", models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CollectorComposeSRPM",
            fields=[
                ("build_id", models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="CollectorComposeRPM",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("nvr", models.TextField(unique=True)),
                (
                    "rhel_module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpms",
                        to="collectors.collectorcomposerhelmodule",
                    ),
                ),
                (
                    "srpm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rpms",
                        to="collectors.collectorcomposesrpm",
                    ),
                ),
            ],
        ),
    ]
