# Generated by Django 3.2.15 on 2022-09-12 05:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0002_collectorcomposerhelmodules"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorerrataproductvariant",
            name="repos",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1024), default=list, size=None
            ),
        ),
    ]
