# Generated by Django 3.2.15 on 2022-09-28 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0003_collectorerrataproductvariant_repos"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CollectorComposeRhelModule",
            new_name="CollectorRhelModule",
        ),
        migrations.RenameModel(
            old_name="CollectorComposeRPM",
            new_name="CollectorRPM",
        ),
        migrations.RenameModel(
            old_name="CollectorComposeSRPM",
            new_name="CollectorSRPM",
        ),
        migrations.CreateModel(
            name="CollectorRPMRepository",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("content_set", models.CharField(max_length=200)),
            ],
        ),
        migrations.AddConstraint(
            model_name="collectorrpm",
            constraint=models.UniqueConstraint(
                fields=("nvra", "srpm"), name="unique_collectorrpms"
            ),
        ),
        migrations.AlterField(
            model_name="collectorrpm",
            name="nvra",
            field=models.TextField(),
        ),
    ]
