# Generated by Django 3.2.18 on 2023-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0005_collectorrpmrepository_relative_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collectorerrataproductvariant",
            name="cpe",
            field=models.TextField(default=""),
        ),
    ]
