# Generated by Django 3.2.20 on 2023-10-19 01:29

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0006_alter_collectorerrataproductvariant_cpe"),
    ]

    operations = [
        migrations.AddField(
            model_name="collectorerrataproduct",
            name="meta_attr",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="collectorerrataproductvariant",
            name="meta_attr",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="collectorerrataproductversion",
            name="meta_attr",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="CollectorErrataRelease",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("et_id", models.IntegerField(unique=True)),
                ("name", models.TextField(unique=True)),
                ("meta_attr", models.JSONField(default=dict)),
                (
                    "brew_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024), default=list, size=None
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("enabled", models.BooleanField(default=False)),
                (
                    "product_versions",
                    models.ManyToManyField(
                        related_name="releases", to="collectors.CollectorErrataProductVersion"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "abstract": False,
            },
        ),
    ]
