# Generated by Django 3.2.20 on 2023-11-17 02:46

import uuid

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0007_add_et_releases"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectorPyxisImage",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("meta_attr", models.JSONField(default=dict)),
                ("image_id", models.CharField(max_length=200)),
                ("arch", models.CharField(max_length=20)),
                ("nvr", models.TextField()),
                ("name_label", models.CharField(default="", max_length=200)),
                ("creation_date", models.DateTimeField()),
                ("pyxis_id", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "ordering": ["uuid"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CollectorPyxisImageRepository",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("meta_attr", models.JSONField(default=dict)),
                ("name", models.CharField(max_length=200)),
                ("registry", models.CharField(max_length=200)),
                ("image_advisory_id", models.CharField(default="", max_length=50)),
                ("manifest_list_digest", models.CharField(max_length=200)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), default=list, size=None
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="repos", to="collectors.CollectorPyxisImage"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="collectorpyxisimagerepository",
            constraint=models.UniqueConstraint(
                fields=("registry", "name"), name="unique_pyxis_repo"
            ),
        ),
    ]
