# Generated by Django 3.2.20 on 2023-11-17 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0008_add_pyxis_image_repos"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="collectorpyxisimagerepository",
            name="unique_pyxis_repo",
        ),
        migrations.AddConstraint(
            model_name="collectorpyxisimagerepository",
            constraint=models.UniqueConstraint(
                fields=("registry", "name", "manifest_list_digest"), name="unique_pyxis_image_repo"
            ),
        ),
    ]
