# Generated by Django 3.2.22 on 2024-01-24 04:08

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("collectors", "0009_add_pyxis_image_repos"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectorSpdxLicense",
            fields=[
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("identifier", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("reference", models.CharField(max_length=200)),
                ("details_url", models.CharField(max_length=200)),
                ("meta_attr", models.JSONField(default=dict)),
            ],
        ),
    ]
