# Generated by Django 3.2.12 on 2022-05-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_auto_20220502_1339"),
    ]

    operations = [
        migrations.AlterField(
            model_name="erratum",
            name="build_id",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="erratum_id",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="erratum",
            name="variant_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
