# Generated by Django 3.2.13 on 2022-05-12 03:06

import uuid

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20220511_1903"),
    ]

    operations = [
        migrations.CreateModel(
            name="RhelCompose",
            fields=[
                ("last_changed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("url", models.CharField(max_length=1024)),
                ("name", models.CharField(max_length=100)),
                (
                    "srpms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024), default=list, size=None
                    ),
                ),
                (
                    "container_images",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024), default=list, size=None
                    ),
                ),
                (
                    "rhel_modules",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=1024), default=list, size=None
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.productvariant"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="Compose",
        ),
    ]
