# Generated by Django 3.2.13 on 2022-05-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_auto_20220513_1006"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Erratum",
        ),
    ]
