# Generated by Django 3.2.13 on 2022-05-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_erratum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componenttag",
            name="name",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="productstreamtag",
            name="name",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="producttag",
            name="name",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="productvarianttag",
            name="name",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="productversiontag",
            name="name",
            field=models.SlugField(max_length=200),
        ),
        migrations.AlterField(
            model_name="softwarebuildtag",
            name="name",
            field=models.SlugField(max_length=200),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["external_system_id", "variant_id", "build_id"],
                name="core_produc_externa_e1ab95_idx",
            ),
        ),
    ]
