# Generated by Django 3.2.13 on 2022-05-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20220517_2054"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="license",
            field=models.TextField(default=""),
        ),
    ]
