# Generated by Django 3.2.13 on 2022-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_component_license"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarebuild",
            name="source",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
