# Generated by Django 3.2.13 on 2022-06-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_softwarebuild_source"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="component",
            name="unique_components",
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("name", "type", "arch", "version", "release", "software_build"),
                name="unique_components",
            ),
        ),
    ]
