# Generated by Django 3.2.13 on 2022-06-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_auto_20220606_1245"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="related_url",
            field=models.CharField(default="", max_length=1024, null=True),  # noqa: DJ01
        ),
    ]
