# Generated by Django 3.2.13 on 2022-06-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_component_related_url"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="component",
            name="unique_components",
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("name", "type", "arch", "version", "release"), name="unique_components"
            ),
        ),
    ]
