# Generated by Django 3.2.13 on 2022-06-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_auto_20220614_1948"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productcomponentrelation",
            name="unique_productcomponentrelation",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_externa_e1ab95_idx",
        ),
        migrations.RenameField(
            model_name="productcomponentrelation",
            old_name="variant_id",
            new_name="product_ref",
        ),
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[("ERRATA", "Errata"), ("COMPOSE", "Compose")], max_length=50
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["external_system_id", "product_ref", "build_id"],
                name="core_produc_externa_abdde1_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcomponentrelation",
            constraint=models.UniqueConstraint(
                fields=("external_system_id", "product_ref", "build_id"),
                name="unique_productcomponentrelation",
            ),
        ),
    ]
