# Generated by Django 3.2.13 on 2022-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_auto_20220620_2110"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="filename",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="product",
            name="lifecycle_url",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="productstream",
            name="lifecycle_url",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="lifecycle_url",
            field=models.CharField(default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="productversion",
            name="lifecycle_url",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
