# Generated by Django 3.2.14 on 2022-07-20 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_auto_20220628_1748"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RhelCompose",
        ),
    ]
