# Generated by Django 3.2.14 on 2022-07-27 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_delete_rhelcompose"),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="upstream",
            new_name="upstreams",
        ),
    ]
