# Generated by Django 3.2.14 on 2022-08-05 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_auto_20220804_0702"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("COMPOSE", "Compose"),
                    ("BREW_TAG", "Brew Tag"),
                    ("YUM_REPO", "Yum Repo"),
                ],
                max_length=50,
            ),
        ),
    ]
