# Generated by Django 3.2.14 on 2022-08-07 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_alter_productcomponentrelation_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(fields=["type", "build_id"], name="core_produc_type_4f4ae4_idx"),
        ),
    ]
