# Generated by Django 3.2.15 on 2022-08-26 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_productcomponentrelation_core_produc_type_4f4ae4_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="componentnode",
            index=models.Index(
                fields=["content_type", "object_id"], name="core_compon_content_61a0fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productnode",
            index=models.Index(
                fields=["content_type", "object_id"], name="core_produc_content_a305f3_idx"
            ),
        ),
    ]
