# Generated by Django 3.2.15 on 2022-09-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_auto_20220907_1948"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["name"], name="core_compon_name_f3d483_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["type"], name="core_compon_type_b2350c_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["nvr"], name="core_compon_nvr_10acc0_idx"),
        ),
        migrations.AddIndex(
            model_name="componentnode",
            index=models.Index(
                fields=["type", "parent", "purl"], name="core_compon_type_1f6187_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["external_system_id"], name="core_produc_externa_2dd410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(fields=["product_ref"], name="core_produc_product_7ae01e_idx"),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(fields=["build_id"], name="core_produc_build_i_b102da_idx"),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(fields=["type"], name="core_produc_type_02062d_idx"),
        ),
    ]
