# Generated by Django 3.2.15 on 2022-09-08 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_auto_20220907_2125"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcomponentrelation",
            options={"ordering": ["external_system_id"]},
        ),
        migrations.AlterModelOptions(
            name="softwarebuild",
            options={"ordering": ["-build_id"]},
        ),
    ]
