# Generated by Django 3.2.15 on 2022-09-08 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_auto_20220908_1435"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="componentnode",
            name="unique_cnode_get_or_create_for_null_parent",
        ),
        migrations.AddConstraint(
            model_name="componentnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("type", "parent", "purl"),
                name="unique_cnode_get_or_create_for_null_parent",
            ),
        ),
    ]
