# Generated by Django 3.2.15 on 2022-09-14 05:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_fix_db_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstream",
            name="et_product_versions",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
    ]
