# Generated by Django 3.2.15 on 2022-09-22 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_auto_20220915_0207"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["purl"], name="core_compon_purl_247d52_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["product_streams"], name="core_compon_product_3e4136_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["product_variants"], name="core_compon_product_f7d627_idx"),
        ),
    ]
