# Generated by Django 3.2.15 on 2022-09-26 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_auto_20220922_0707"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["type", "name"], name="core_compon_type_2a0006_idx"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["type", "product_streams"], name="core_compon_type_b2214a_idx"
            ),
        ),
    ]
