# Generated by Django 3.2.15 on 2022-09-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_auto_20220926_1245"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("COMPOSE", "Compose"),
                    ("BREW_TAG", "Brew Tag"),
                    ("CDN_REPO", "Cdn Repo"),
                    ("YUM_REPO", "Yum Repo"),
                ],
                max_length=50,
            ),
        ),
    ]
