# Generated by Django 3.2.15 on 2022-10-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_productcomponentrelation_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["product_ref", "type"], name="core_produc_product_c88392_idx"
            ),
        ),
    ]
