# Generated by Django 3.2.15 on 2022-10-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_custom_indexes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="component",
            old_name="license",
            new_name="license_declared_raw",
        ),
        migrations.AddField(
            model_name="component",
            name="copyright_text",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="component",
            name="license_concluded_raw",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="component",
            name="openlcs_scan_url",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="component",
            name="openlcs_scan_version",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="component",
            name="related_url",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
