# Generated by Django 3.2.15 on 2022-10-13 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_olcs_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarebuild",
            name="completion_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="software_build",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="core.softwarebuild",
            ),
        ),
        migrations.AddIndex(
            model_name="softwarebuild",
            index=models.Index(fields=["completion_time"], name="core_softwa_complet_c38fc7_idx"),
        ),
    ]
