# Generated by Django 3.2.15 on 2022-10-13 07:48

import django.db.models.deletion
from django.db import migrations, models
from django.utils import dateparse
from django.utils.timezone import make_aware


def set_software_build_completion_time(apps, schema_editor):
    SoftwareBuild = apps.get_model("core", "SoftwareBuild")
    for sb in SoftwareBuild.objects.all():
        sb.completion_time = make_aware(
            dateparse.parse_datetime(sb.meta_attr["completion_time"].split(".")[0])
        )
        sb.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_add_olcs_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="softwarebuild",
            name="completion_time",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="component",
            name="software_build",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="components",
                to="core.softwarebuild",
            ),
        ),
        migrations.AddIndex(
            model_name="softwarebuild",
            index=models.Index(fields=["completion_time"], name="core_softwa_complet_c38fc7_idx"),
        ),
        migrations.RunPython(set_software_build_completion_time),
    ]
