# Generated by Django 3.2.15 on 2022-10-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_auto_20221013_0748"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["ofuri"], name="core_produc_ofuri_671dbe_idx"),
        ),
        migrations.AddIndex(
            model_name="productstream",
            index=models.Index(fields=["ofuri"], name="core_produc_ofuri_e77387_idx"),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["ofuri"], name="core_produc_ofuri_ccf4bd_idx"),
        ),
        migrations.AddIndex(
            model_name="productversion",
            index=models.Index(fields=["ofuri"], name="core_produc_ofuri_c62cf2_idx"),
        ),
    ]
