# Generated by Django 3.2.15 on 2022-10-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_auto_20221020_1057"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="component",
            options={"ordering": ("type", "name")},
        ),
    ]
