# Generated by Django 3.2.15 on 2022-10-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_autovacuum"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="namespace",
            field=models.CharField(
                choices=[("UPSTREAM", "Upstream"), ("REDHAT", "Redhat")], default="", max_length=20
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="component",
            name="type",
            field=models.CharField(
                choices=[
                    ("CARGO", "Cargo"),
                    ("OCI", "Container Image"),
                    ("GEM", "Gem"),
                    ("GENERIC", "Generic"),
                    ("GITHUB", "Github"),
                    ("GOLANG", "Golang"),
                    ("MAVEN", "Maven"),
                    ("NPM", "Npm"),
                    ("RPMMOD", "Rpmmod"),
                    ("RPM", "Rpm"),
                    ("PYPI", "Pypi"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="softwarebuild",
            name="type",
            field=models.CharField(choices=[("BREW", "Brew"), ("KOJI", "Koji")], max_length=20),
        ),
        migrations.RunSQL("DROP INDEX IF EXISTS core_compon_latest_name_type_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS core_compon_latest_type_name_idx"),
        migrations.RunSQL("DROP INDEX IF EXISTS core_compon_latest_idx"),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(
                        models.Q(("type", "RPM"), ("arch", "src")),
                        ("type", "RPMMOD"),
                        models.Q(("type", "OCI"), ("arch", "noarch")),
                        _connector="OR",
                    )
                ),
                fields=["type", "name", "arch"],
                name="compon_latest_name_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(
                        models.Q(("type", "RPM"), ("arch", "src")),
                        ("type", "RPMMOD"),
                        models.Q(("type", "OCI"), ("arch", "noarch")),
                        _connector="OR",
                    )
                ),
                fields=["name", "type", "arch"],
                name="compon_latest_type_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(
                        models.Q(("type", "RPM"), ("arch", "src")),
                        ("type", "RPMMOD"),
                        models.Q(("type", "OCI"), ("arch", "noarch")),
                        _connector="OR",
                    )
                ),
                fields=["uuid", "software_build_id", "type", "name", "arch", "product_streams"],
                name="compon_latest_idx",
            ),
        ),
    ]
