# Generated by Django 3.2.15 on 2022-10-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_adjust_purls_for_external_consumption"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="relative_url",
            field=models.CharField(default="", max_length=200),
        ),
    ]
