# Generated by Django 3.2.15 on 2022-10-31 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_channel_relative_url"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="appstreamlifecycle",
            options={},
        ),
        migrations.AlterModelOptions(
            name="channel",
            options={},
        ),
        migrations.AlterModelOptions(
            name="component",
            options={},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productcomponentrelation",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productstream",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productvariant",
            options={},
        ),
        migrations.AlterModelOptions(
            name="productversion",
            options={},
        ),
        migrations.AlterModelOptions(
            name="softwarebuild",
            options={},
        ),
    ]
