# Generated by Django 3.2.15 on 2022-10-31 20:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_fix_model_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="componenttag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="componenttag",
            name="last_changed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productstreamtag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productstreamtag",
            name="last_changed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="producttag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="producttag",
            name="last_changed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productvarianttag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productvarianttag",
            name="last_changed",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="productversiontag",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productversiontag",
            name="last_changed",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
