# Generated by Django 3.2.15 on 2022-10-31 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_fix_missing_field_for_tag_serializer"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="componenttag",
            name="unique_componenttag",
        ),
        migrations.RemoveConstraint(
            model_name="productstreamtag",
            name="unique_productstreamtag",
        ),
        migrations.RemoveConstraint(
            model_name="producttag",
            name="unique_producttag",
        ),
        migrations.RemoveConstraint(
            model_name="productvarianttag",
            name="unique_productvarianttag",
        ),
        migrations.RemoveConstraint(
            model_name="productversiontag",
            name="unique_productversiontag",
        ),
        migrations.RemoveConstraint(
            model_name="softwarebuildtag",
            name="unique_softwarebuildtag",
        ),
        migrations.RenameField(
            model_name="componenttag",
            old_name="component",
            new_name="tagged_model",
        ),
        migrations.RenameField(
            model_name="productstreamtag",
            old_name="product_stream",
            new_name="tagged_model",
        ),
        migrations.RenameField(
            model_name="producttag",
            old_name="product",
            new_name="tagged_model",
        ),
        migrations.RenameField(
            model_name="productvarianttag",
            old_name="product_variant",
            new_name="tagged_model",
        ),
        migrations.RenameField(
            model_name="productversiontag",
            old_name="product_version",
            new_name="tagged_model",
        ),
        migrations.RenameField(
            model_name="softwarebuildtag",
            old_name="software_build",
            new_name="tagged_model",
        ),
        migrations.AddConstraint(
            model_name="componenttag",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "tagged_model"), name="unique_componenttag"
            ),
        ),
        migrations.AddConstraint(
            model_name="productstreamtag",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "tagged_model"), name="unique_productstreamtag"
            ),
        ),
        migrations.AddConstraint(
            model_name="producttag",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "tagged_model"), name="unique_producttag"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvarianttag",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "tagged_model"), name="unique_productvarianttag"
            ),
        ),
        migrations.AddConstraint(
            model_name="productversiontag",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "tagged_model"), name="unique_productversiontag"
            ),
        ),
        migrations.AddConstraint(
            model_name="softwarebuildtag",
            constraint=models.UniqueConstraint(
                fields=("name", "value", "tagged_model"), name="unique_softwarebuildtag"
            ),
        ),
    ]
