# Generated by Django 3.2.15 on 2022-11-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_make_tagging_generic"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="componentnode",
            index=models.Index(
                fields=["object_id", "parent"], name="core_compon_object__d7d955_idx"
            ),
        ),
    ]
