# Generated by Django 3.2.15 on 2022-11-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_fix_mptt_property_ordering"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_name_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_type_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_idx",
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    ("type", "RPMMOD"),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    _connector="OR",
                ),
                fields=["type", "name", "arch"],
                name="compon_latest_name_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    ("type", "RPMMOD"),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    _connector="OR",
                ),
                fields=["name", "type", "arch"],
                name="compon_latest_type_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    ("type", "RPMMOD"),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    _connector="OR",
                ),
                fields=["uuid", "software_build_id", "type", "name", "arch", "product_streams"],
                name="compon_latest_idx",
            ),
        ),
    ]
