# Generated by Django 3.2.15 on 2022-11-04 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_mostly_noop_index_change"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_streams",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_variants",
        ),
        migrations.RemoveField(
            model_name="product",
            name="product_versions",
        ),
        migrations.RemoveField(
            model_name="productstream",
            name="product_variants",
        ),
        migrations.RemoveField(
            model_name="productstream",
            name="product_versions",
        ),
        migrations.RemoveField(
            model_name="productstream",
            name="products",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="product_streams",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="product_versions",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="products",
        ),
        migrations.RemoveField(
            model_name="productversion",
            name="product_streams",
        ),
        migrations.RemoveField(
            model_name="productversion",
            name="product_variants",
        ),
        migrations.RemoveField(
            model_name="productversion",
            name="products",
        ),
        migrations.AddField(
            model_name="productstream",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productstreams",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="productstream",
            name="productversions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productstreams",
                to="core.productversion",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariants",
                to="core.product",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="productstreams",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariants",
                to="core.productstream",
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="productversions",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariants",
                to="core.productversion",
            ),
        ),
        migrations.AddField(
            model_name="productversion",
            name="products",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productversions",
                to="core.product",
            ),
        ),
    ]
