# Generated by Django 3.2.15 on 2022-11-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_use_foreign_keys_for_product_taxonomy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstream",
            name="channels",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="product_streams",
        ),
        migrations.AddField(
            model_name="channel",
            name="productstreams",
            field=models.ManyToManyField(related_name="channels", to="core.ProductStream"),
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="channels",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="product_variants",
        ),
        migrations.AddField(
            model_name="channel",
            name="productvariants",
            field=models.ManyToManyField(related_name="channels", to="core.ProductVariant"),
        ),
        migrations.RemoveField(
            model_name="productversion",
            name="channels",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="product_versions",
        ),
        migrations.AddField(
            model_name="channel",
            name="productversions",
            field=models.ManyToManyField(related_name="channels", to="core.ProductVersion"),
        ),
        migrations.RemoveField(
            model_name="product",
            name="channels",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="products",
        ),
        migrations.AddField(
            model_name="channel",
            name="products",
            field=models.ManyToManyField(related_name="channels", to="core.Product"),
        ),
    ]
