# Generated by Django 3.2.15 on 2022-11-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_use_many_to_many_fields_for_channel_taxonomy"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="core_compon_product_3e4136_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="core_compon_product_f7d627_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="core_compon_type_b2214a_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_idx",
        ),
        migrations.RemoveField(
            model_name="component",
            name="product_streams",
        ),
        migrations.RemoveField(
            model_name="component",
            name="product_variants",
        ),
        migrations.RemoveField(
            model_name="component",
            name="product_versions",
        ),
        migrations.RemoveField(
            model_name="component",
            name="provides",
        ),
        migrations.AddField(
            model_name="component",
            name="productstreams",
            field=models.ManyToManyField(related_name="components", to="core.ProductStream"),
        ),
        migrations.AddField(
            model_name="component",
            name="productvariants",
            field=models.ManyToManyField(related_name="components", to="core.ProductVariant"),
        ),
        migrations.AddField(
            model_name="component",
            name="productversions",
            field=models.ManyToManyField(related_name="components", to="core.ProductVersion"),
        ),
        migrations.RemoveField(
            model_name="component",
            name="channels",
        ),
        migrations.AddField(
            model_name="component",
            name="channels",
            field=models.ManyToManyField(to="core.Channel"),
        ),
        migrations.RemoveField(
            model_name="component",
            name="products",
        ),
        migrations.AddField(
            model_name="component",
            name="products",
            field=models.ManyToManyField(related_name="components", to="core.Product"),
        ),
        migrations.RemoveField(
            model_name="component",
            name="sources",
        ),
        migrations.AddField(
            model_name="component",
            name="sources",
            field=models.ManyToManyField(related_name="provides", to="core.Component"),
        ),
        migrations.RemoveField(
            model_name="component",
            name="upstreams",
        ),
        migrations.AddField(
            model_name="component",
            name="upstreams",
            field=models.ManyToManyField(to="core.Component"),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    ("type", "RPMMOD"),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    _connector="OR",
                ),
                fields=["uuid", "software_build_id", "type", "name", "arch"],
                name="compon_latest_idx",
            ),
        ),
    ]
