# Generated by Django 3.2.15 on 2022-11-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0052_use_many_to_many_fields_for_component_taxonomies"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="core_compon_name_f3d483_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="core_compon_type_b2350c_idx",
        ),
        migrations.RemoveIndex(
            model_name="componentnode",
            name="core_compon_type_b33d5b_idx",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_externa_2dd410_idx",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_product_7ae01e_idx",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_type_02062d_idx",
        ),
    ]
