# Generated by Django 3.2.15 on 2023-01-16 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0054_auto_20221124_0931"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="arch",
            field=models.CharField(
                choices=[
                    ("aarch64", "Aarch64"),
                    ("i386", "I386"),
                    ("i686", "I686"),
                    ("ia64", "Ia64"),
                    ("noarch", "Noarch"),
                    ("ppc", "Ppc"),
                    ("ppc64", "Ppc64"),
                    ("ppc64le", "Ppc64Le"),
                    ("s390", "S390"),
                    ("s390x", "S390X"),
                    ("src", "Src"),
                    ("x86_64", "X86 64"),
                ],
                max_length=20,
            ),
        ),
    ]
