# Generated by Django 3.2.15 on 2023-01-13 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_auto_20230117_1049"),
    ]

    operations = [
        migrations.RenameField(
            model_name="softwarebuild",
            old_name="type",
            new_name="build_type",
        ),
    ]
