# Generated by Django 3.2.16 on 2023-01-29 12:44

import django.contrib.postgres.fields
from django.db import migrations, models

from corgi.core.constants import ROOT_COMPONENTS_CONDITION


def set_release_version_arr(apps, schema_editor):
    """Set version_arr, release_arr and el_match by saving all root
    components (noarch OCI and src RPM)."""
    Component = apps.get_model("core", "Component")
    for sb in Component.objects.filter(ROOT_COMPONENTS_CONDITION).iterator():
        sb.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_rename_type_softwarebuild_build_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="el_match",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="release_arr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="version_arr",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
        migrations.RunPython(set_release_version_arr),
    ]
