# Generated by Django 3.2.18 on 2023-03-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_add_version_release_arr_fields"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=models.Index(fields=["nevra"], name="core_compon_nevra_4ac59e_idx"),
        ),
    ]
