# Generated by Django 3.2.15 on 2022-12-23 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_change_software_build_primary_key"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productcomponentrelation",
            name="unique_productcomponentrelation",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_externa_abdde1_idx",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_type_4f4ae4_idx",
        ),
        migrations.RemoveIndex(
            model_name="productcomponentrelation",
            name="core_produc_build_i_b102da_idx",
        ),
        migrations.AddField(
            model_name="productcomponentrelation",
            name="build_type",
            field=models.CharField(
                choices=[("BREW", "Brew"), ("KOJI", "Koji"), ("CENTOS", "Centos")],
                default="BREW",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="softwarebuild",
            name="build_type",
            field=models.CharField(
                choices=[("BREW", "Brew"), ("KOJI", "Koji"), ("CENTOS", "Centos")], max_length=20
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["external_system_id", "product_ref", "build_id", "build_type"],
                name="core_produc_externa_6c83e4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["type", "build_id", "build_type"], name="core_produc_type_fc2c0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponentrelation",
            index=models.Index(
                fields=["build_id", "build_type"], name="core_produc_build_i_f6e300_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcomponentrelation",
            constraint=models.UniqueConstraint(
                fields=("external_system_id", "product_ref", "build_id", "build_type"),
                name="unique_productcomponentrelation",
            ),
        ),
    ]
