# Generated by Django 3.2.18 on 2023-03-07 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_component_core_compon_nevra_4ac59e_idx"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="componentnode",
            name="core_compon_purl_bf2311_idx",
        ),
        migrations.RunSQL("DROP INDEX core_cn_lft_tree_idx"),
        migrations.RunSQL("DROP INDEX core_componentnode_parent_id_be93cab7"),
        migrations.RunSQL("DROP INDEX core_componentnode_content_type_id_334077a8"),
        migrations.RunSQL("DROP INDEX core_component_channels_component_id_9c8754af"),
    ]
