# Generated by Django 3.2.18 on 2023-03-14 15:26

from django.db import migrations, models


def fix_duplicate_purls(apps, schema_editor):
    """Delete Syft-created Python components with duplicate / ambiguous purls"""
    Component = apps.get_model("core", "Component")
    for dupe_pk, dupe_purl in (
        Component.objects.filter(type="PYPI", meta_attr__source="syft-0.60.1")
        .values_list("pk", "purl")
        .iterator()
    ):
        if Component.objects.filter(purl=dupe_purl).count() > 1:
            Component.objects.filter(pk=dupe_pk).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_remove_large_unused_indexes"),
    ]

    operations = [
        migrations.RunPython(fix_duplicate_purls),
        migrations.AlterField(
            model_name="component",
            name="purl",
            field=models.CharField(default="", max_length=1024, unique=True),
        ),
    ]
