# Generated by Django 3.2.18 on 2023-03-15 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_remove_large_unused_indexes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="purl",
            field=models.CharField(default="", max_length=1024, unique=True),
        ),
    ]
