# Generated by Django 3.2.18 on 2023-03-30 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0062_add_build_type_to_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="softwarebuild",
            name="build_id",
            field=models.CharField(default="", max_length=200),
        ),
    ]
