# Generated by Django 3.2.18 on 2023-04-13 15:24

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0063_alter_softwarebuild_build_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedHatUser",
            fields=[
                (
                    "rhat_uuid",
                    models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
                ),
                ("rhat_roles", models.TextField(default="")),
                ("cn", models.CharField(default="", max_length=256)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
