# Generated by Django 3.2.18 on 2023-04-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0065_redhatprofile"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="softwarebuild",
            name="core_softwa_complet_c38fc7_idx",
        ),
        migrations.AddIndex(
            model_name="softwarebuild",
            index=models.Index(
                fields=["build_id", "build_type"], name="core_softwa_build_i_c34fd9_idx"
            ),
        ),
    ]
