# Generated by Django 3.2.18 on 2023-05-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0066_adjust_softwarebuild_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="epoch",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunSQL(
            "UPDATE core_component SET epoch = (meta_attr->>'epoch')::integer"
            " WHERE meta_attr->>'epoch' is not NULL"
            " AND meta_attr->>'epoch' != '0'"
        ),
    ]
