# Generated by Django 3.2.18 on 2023-06-06 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_fix_missing_go_component_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="release_arr",
        ),
        migrations.RemoveField(
            model_name="component",
            name="version_arr",
        ),
    ]
