# Generated by Django 3.2.18 on 2023-06-19 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_fix_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomponentrelation",
            name="software_build",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="relations",
                to="core.softwarebuild",
            ),
        ),
    ]
