# Generated by Django 3.2.18 on 2023-06-19 02:18

from django.db import migrations, transaction


def update_build_to_sb_fk(apps, schema_editor):
    ProductComponentRelation = apps.get_model("core", "ProductComponentRelation")
    SoftwareBuild = apps.get_model("core", "SoftwareBuild")
    for relation in ProductComponentRelation.objects.filter(software_build__isnull=True).iterator():
        with transaction.atomic():
            sb = SoftwareBuild.objects.filter(
                build_id=relation.build_id, build_type=relation.build_type
            ).first()
            if sb:
                relation.software_build = sb
                relation.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_productcomponentrelation_software_build"),
    ]

    operations = [migrations.RunPython(update_build_to_sb_fk)]
