# Generated by Django 3.2.18 on 2023-06-19 02:18

from django.db import migrations


def update_build_to_sb_fk(apps, schema_editor):
    ProductComponentRelation = apps.get_model("core", "ProductComponentRelation")
    SoftwareBuild = apps.get_model("core", "SoftwareBuild")

    relation_build_ids = (
        ProductComponentRelation.objects.filter(software_build__isnull=True)
        .values_list("build_id", flat=True)
        .order_by()
        .distinct()
    )
    existing_build_ids = (
        SoftwareBuild.objects.filter(build_id__in=relation_build_ids)
        .values_list("build_id", "build_type", "pk")
        .order_by()
    )
    for build_id, build_type, pk in existing_build_ids.iterator():
        ProductComponentRelation.filter(build_id=build_id, build_type=build_type).order_by().update(
            software_build=pk
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_productcomponentrelation_software_build"),
    ]

    operations = [migrations.RunPython(update_build_to_sb_fk)]
