# Generated by Django 3.2.18 on 2023-06-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_productcomponentrelation_sb_fk_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="upstreams",
            field=models.ManyToManyField(related_name="downstreams", to="core.Component"),
        ),
    ]
