# Generated by Django 3.2.18 on 2023-06-19 02:18

from django.db import migrations, models

# Non-historical model, i.e. if you change save_product_taxonomy() tomorrow
# the migration will not run the same code as before (at the time the migration was written)
from corgi.core.models import SoftwareBuild as CurrentSBModel


def remove_cdn_repo_relations(apps, schema_editor):
    """Remove CDN_REPO relations created by the Pulp collector,
    then fix the product taxonomy on all builds / components that had these relations"""
    Component = apps.get_model("core", "Component")
    ProductComponentRelation = apps.get_model("core", "ProductComponentRelation")

    provides_through = Component.provides.through.objects
    upstreams_through = Component.upstreams.through.objects

    channels_through = Component.channels.through.objects
    variants_through = Component.productvariants.through.objects
    streams_through = Component.productstreams.through.objects
    versions_through = Component.productversions.through.objects
    products_through = Component.products.through.objects

    # Hardcoding the constant because we want to remove this type from the model
    for build_pk in (
        ProductComponentRelation.objects.filter(type="CDN_REPO", software_build_id__isnull=False)
        .values_list("software_build_id", flat=True)
        .distinct()
        .iterator()
    ):
        # Fix all components on builds that have CDN_REPO relations
        root_component = Component.objects.get(software_build_id=build_pk)
        # Fix the root components linked directly to this build
        # Clear the Variant / Channel links since they're wrong
        # We only append to links when saving taxonomies
        # So to remove bad data and add the right data
        # We need to clear first, and then reprocess afterwards
        root_component.channels.clear()
        root_component.productvariants.clear()

        # Also clear the stream / version / product links
        # We add the parents of some Variant to this Component
        # Since the Variant is now gone, remove its parents as well
        # Should be a no-op in most cases, we'll add back all products
        # that were removed using other relations
        # But when a build no longer relates to any Variants
        # we want to handle this edge case and unlink it from everything
        root_component.productstreams.clear()
        root_component.productversions.clear()
        root_component.products.clear()

        root_component_provides = provides_through.filter(
            to_component_id=root_component
        ).values_list("from_component_id", flat=True)
        root_component_upstreams = upstreams_through.filter(
            from_component_id=root_component
        ).values_list("to_component_id", flat=True)

        channels_through.filter(component_id__in=root_component_provides).delete()
        channels_through.filter(component_id__in=root_component_upstreams).delete()

        variants_through.filter(component_id__in=root_component_provides).delete()
        variants_through.filter(component_id__in=root_component_upstreams).delete()

        streams_through.filter(component_id__in=root_component_provides).delete()
        streams_through.filter(component_id__in=root_component_upstreams).delete()

        versions_through.filter(component_id__in=root_component_provides).delete()
        versions_through.filter(component_id__in=root_component_upstreams).delete()

        products_through.filter(component_id__in=root_component_provides).delete()
        products_through.filter(component_id__in=root_component_upstreams).delete()

        # Delete CDN_REPO relations for this build, then fix taxonomies
        ProductComponentRelation.objects.filter(
            software_build_id=build_pk, type="CDN_REPO"
        ).delete()
        # Add the correct Component-Variant links on all Components in this build
        # using the current model because we need to call save_product_taxonomy()
        # but apps.get_model() doesn't let us run custom code
        CurrentSBModel.objects.get(uuid=build_pk).save_product_taxonomy()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_fix_component_upstreams_and_software_builds"),
    ]

    operations = [
        migrations.RunPython(remove_cdn_repo_relations),
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("COMPOSE", "Compose"),
                    ("BREW_TAG", "Brew Tag"),
                    ("YUM_REPO", "Yum Repo"),
                    ("APP_INTERFACE", "App Interface"),
                ],
                max_length=50,
            ),
        ),
    ]
