# Generated by Django 3.2.18 on 2023-06-19 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0073_fix_component_upstreams_and_software_builds"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("COMPOSE", "Compose"),
                    ("BREW_TAG", "Brew Tag"),
                    ("YUM_REPO", "Yum Repo"),
                    ("APP_INTERFACE", "App Interface"),
                ],
                max_length=50,
            ),
        ),
    ]
