# Generated by Django 3.2.18 on 2023-06-19 02:18

from django.db import migrations


def fix_channel_variant_component_links(apps, schema_editor):
    """Remove Channel-Component links for all Components, then
    clear and reprocess all Variant-Component links for Variant-type relations"""
    Component = apps.get_model("core", "Component")
    SoftwareBuild = apps.get_model("core", "SoftwareBuild")

    # Clear links to Channels on all Components
    Component.channels.through.objects.get_queryset().delete()

    # ERRATA relations are the only Variant-type relation
    # after we removed CDN_REPO relations in migration #0073
    for build in SoftwareBuild.objects.filter(relations__type="ERRATA").iterator():
        # Fix all components on builds that have Variant-type relations
        for component in build.components.get_queryset().iterator():
            # Fix the root components linked directly to this build
            # Clear the Variant / Channel links since they're wrong
            # We only append to links when saving taxonomies
            # So to remove bad data and add the right data
            # We need to clear first, and then reprocess afterwards
            component.productvariants.clear()

            # Also clear the stream / version / product links
            # We add the parents of some Variant to this Component
            # Since the Variant is now gone, remove its parents as well
            # Should be a no-op in most cases, we'll add back all products
            # that were removed using other relations
            # But when a build no longer relates to any Variants
            # we want to handle this edge case and unlink it from everything
            component.productstreams.clear()
            component.productversions.clear()
            component.products.clear()

            for provided_component in component.provides.get_queryset().iterator():
                # Fix the provided components
                # They aren't always linked to the build, so can't be handled above
                provided_component.productvariants.clear()
                provided_component.productstreams.clear()
                provided_component.productversions.clear()
                provided_component.products.clear()

            for upstream_component in component.upstreams.get_queryset().iterator():
                # Fix the upstream components
                # They aren't ever linked to the build, so can't be handled above
                upstream_component.productvariants.clear()
                upstream_component.productstreams.clear()
                upstream_component.productversions.clear()
                upstream_component.products.clear()

        # Add the correct Component-Variant links on all Components in this build
        build.save_product_taxonomy()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0074_remove_cdn_repo_relations"),
    ]

    operations = [migrations.RunPython(fix_channel_variant_component_links)]
