# Generated by Django 3.2.20 on 2023-07-12 17:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0075_fix_oci_purls"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstream",
            name="exclude_components",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=200), default=list, size=None
            ),
        ),
    ]
