# Generated by Django 3.2.18 on 2023-07-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_clear_component_channels"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_name_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_type_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_idx",
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    models.Q(("arch", "noarch"), ("namespace", "REDHAT"), ("type", "GITHUB")),
                    _connector="OR",
                ),
                fields=["type", "name", "arch"],
                name="compon_latest_name_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    models.Q(("arch", "noarch"), ("namespace", "REDHAT"), ("type", "GITHUB")),
                    _connector="OR",
                ),
                fields=["name", "type", "arch"],
                name="compon_latest_type_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    models.Q(("arch", "noarch"), ("namespace", "REDHAT"), ("type", "GITHUB")),
                    _connector="OR",
                ),
                fields=["uuid", "software_build_id", "type", "name", "arch"],
                name="compon_latest_idx",
            ),
        ),
    ]
