# Generated by Django 3.2.18 on 2023-06-23 14:51

import django.db.models.deletion
from django.db import migrations, models


def set_componentnode_foreign_key(apps, schema_editor):
    """Set a ComponentNode's ForeignKey to the matching Component,
    using the preexisting object_id from the GenericForeignKey"""
    ComponentNode = apps.get_model("core", "ComponentNode")
    ComponentNode.objects.filter(component__isnull=True).update(component=models.F("object_id"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_clear_component_channels"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentnode",
            name="component",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cnodes",
                to="core.component",
            ),
        ),
        migrations.RunPython(set_componentnode_foreign_key),
        migrations.AlterField(
            model_name="componentnode",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cnodes",
                to="core.component",
            ),
        ),
        migrations.AddIndex(
            model_name="componentnode",
            index=models.Index(
                fields=["component", "parent"], name="core_compon_compone_aa17a4_idx"
            ),
        ),
    ]
