# Generated by Django 3.2.18 on 2023-06-19 02:18

from django.db import migrations, models

from corgi.tasks.brew import slow_save_taxonomy


def fix_variant_component_links(apps, schema_editor):
    """Clear and reprocess all Variant-Component links for Variant-type relations"""
    ProductComponentRelation = apps.get_model("core", "ProductComponentRelation")

    # ERRATA relations are the only Variant-type relation
    # after we removed CDN_REPO relations in migration #0074
    # We still need to clear links created by old code
    # See commit history or CORGI-566 for details
    for build_id, build_type in (
        ProductComponentRelation.objects.filter(type="ERRATA", software_build_id__isnull=False)
        .values_list("build_id", "build_type")
        .distinct()
        .iterator()
    ):
        # Add the correct Component-Variant links on all Components in this build
        # by calling slow_save_taxonomy()
        # TODO: Fix the CDN_REPO relations like I tried in migration #0074 - see commit history
        slow_save_taxonomy.delay(build_id, build_type)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_add_services_repo_to_root_components"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="component",
            name="productvariants",
        ),
        migrations.AddField(
            model_name="component",
            name="productvariants",
            field=models.ManyToManyField(related_name="components", to="core.ProductVariant"),
        ),
        # Remove all the links above, then add back only the good ones below
        migrations.RunPython(fix_variant_component_links),
    ]
