# Generated by Django 3.2.18 on 2023-07-17 04:27

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_fix_component_variants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstream",
            name="cpe",
        ),
        migrations.AddField(
            model_name="productversion",
            name="cpe_patterns",
            field=ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
        migrations.AddField(
            model_name="productversion",
            name="cpes_matching_patterns",
            field=ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
        migrations.AddField(
            model_name="productstream",
            name="cpes_matching_patterns",
            field=ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
