# Generated by Django 3.2.19 on 2023-08-21 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_set_build_fk_relations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="build_type",
            field=models.CharField(
                choices=[
                    ("BREW", "Brew"),
                    ("KOJI", "Koji"),
                    ("CENTOS", "Centos"),
                    ("APP_INTERFACE", "App Interface"),
                    ("PNC", "Pnc"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("COMPOSE", "Compose"),
                    ("BREW_TAG", "Brew Tag"),
                    ("YUM_REPO", "Yum Repo"),
                    ("APP_INTERFACE", "App Interface"),
                    ("SBOMER", "Sbomer"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="softwarebuild",
            name="build_type",
            field=models.CharField(
                choices=[
                    ("BREW", "Brew"),
                    ("KOJI", "Koji"),
                    ("CENTOS", "Centos"),
                    ("APP_INTERFACE", "App Interface"),
                    ("PNC", "Pnc"),
                ],
                max_length=20,
            ),
        ),
    ]
