# Generated by Django 3.2.18 on 2023-08-21 01:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_sbomer"),
    ]

    operations = [
        migrations.AddField(
            model_name="productstream",
            name="cpes_from_brew_tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=1000), default=list, size=None
            ),
        ),
    ]
