# Generated by Django 3.2.20 on 2023-08-31 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0087_add_rpmmod_to_root_component_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomponentrelation",
            name="type",
            field=models.CharField(
                choices=[
                    ("ERRATA", "Errata"),
                    ("COMPOSE", "Compose"),
                    ("BREW_TAG", "Brew Tag"),
                    ("CDN_REPO", "Cdn Repo"),
                    ("YUM_REPO", "Yum Repo"),
                    ("APP_INTERFACE", "App Interface"),
                    ("SBOMER", "Sbomer"),
                ],
                max_length=50,
            ),
        ),
    ]
