# Generated by Django 3.2.20 on 2023-10-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_install_stored_proc"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_idx",
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(
                    models.Q(("arch", "src"), ("type", "RPM")),
                    ("type", "RPMMOD"),
                    models.Q(("arch", "noarch"), ("type", "OCI")),
                    models.Q(("arch", "noarch"), ("namespace", "REDHAT"), ("type", "GITHUB")),
                    _connector="OR",
                ),
                fields=["uuid", "name", "namespace", "software_build_id", "type", "arch"],
                name="compon_latest_idx",
            ),
        ),
    ]
