# Generated by Django 3.2.20 on 2023-10-16 19:19

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0095_clean_rpmlint_invalid_syft_deps"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="component",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="compon_search_name", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["purl"], name="compon_search_purl", opclasses=["gin_trgm_ops"]
            ),
        ),
    ]
