# Generated by Django 3.2.20 on 2023-10-16 19:19

from django.contrib.postgres.operations import BtreeGinExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_fix_nevra_formatting"),
    ]

    operations = [
        # install gin/trgrm postgres extensions
        BtreeGinExtension(),
        TrigramExtension(),
        # setting gin indexes with gin_trgm_ops does not work when define on
        # django Component model indexes - so we set them manually
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compons_search_name ON core_component USING gin (name gin_trgm_ops);"  # noqa: E501
        ),
        migrations.RunSQL(
            "CREATE INDEX IF NOT EXISTS compons_search_purl ON core_component USING gin (purl gin_trgm_ops);"  # noqa: E501
        ),
    ]
