# Generated by Django 3.2.20 on 2023-11-02 19:36

from django.db import migrations, models

from corgi.core.constants import GET_LATEST_COMPONENT_STOREDPROC_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0103_fix_duplicate_remote_source_components"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_name_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_type_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="component",
            name="compon_latest_idx",
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(("software_build_id__isnull", False)),
                fields=["type", "name", "arch"],
                name="compon_latest_name_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(("software_build_id__isnull", False)),
                fields=["name", "type", "arch"],
                name="compon_latest_type_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                condition=models.Q(("software_build_id__isnull", False)),
                fields=["uuid", "name", "namespace", "software_build_id", "type", "arch"],
                name="compon_latest_idx",
            ),
        ),
        migrations.RunSQL(GET_LATEST_COMPONENT_STOREDPROC_SQL),
    ]
