# Generated by Django 3.2.20 on 2023-11-05 23:59

from django.db import migrations

from corgi.core.models import Component, SoftwareBuild
from corgi.tasks.pyxis import slow_update_name_for_container_from_pyxis


def get_latest_repo_names_from_pyxis(apps, schema_editor) -> None:
    brew_container_nvrs = (
        Component.objects.filter(
            type=Component.Type.CONTAINER_IMAGE, software_build__build_type=SoftwareBuild.Type.BREW
        )
        .exclude(meta_attr__has_key="name_from_label_raw")
        .values_list("nvr", flat=True)
        .iterator()
    )
    for nvr in brew_container_nvrs:
        slow_update_name_for_container_from_pyxis.delay(nvr)


class Migration(migrations.Migration):

    dependencies = [("core", "0104_fix_root_components_condition")]

    operations = [
        migrations.RunPython(get_latest_repo_names_from_pyxis),
    ]
