# Generated by Django 3.2.20 on 2023-11-02 19:36

from django.db import migrations

from corgi.core.constants import GET_LATEST_COMPONENT_STOREDPROC_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_get_latest_repo_names_from_pyxis"),
    ]

    operations = [
        migrations.RunSQL(GET_LATEST_COMPONENT_STOREDPROC_SQL),
    ]
