# Generated by Django 3.2.22 on 2023-11-30 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_exclude_module_src_from_root_components_condition"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productnode",
            name="unique_pnode_get_or_create",
        ),
        migrations.RemoveConstraint(
            model_name="productnode",
            name="unique_pnode_get_or_create_for_null_parent",
        ),
        migrations.AddField(
            model_name="productnode",
            name="type",
            field=models.CharField(
                choices=[("DIRECT", "Direct"), ("INFERRED", "Inferred")],
                default="DIRECT",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="productnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("object_id", "parent", "type"),
                name="unique_pnode_get_or_create",
            ),
        ),
        migrations.AddConstraint(
            model_name="productnode",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("object_id", "type"),
                name="unique_pnode_get_or_create_for_null_parent",
            ),
        ),
    ]
