# Generated by Django 3.2.20 on 2023-11-23 04:48

from django.db import migrations

from corgi.core.models import ComponentNode
from corgi.tasks.common import slow_save_taxonomy as current_slow_save_taxonony


def save_container_taxonomy(apps, schema_editor) -> None:
    Component = apps.get_model("core", "Component")
    for root_container in Component.objects.filter(type="OCI", arch="noarch").iterator():
        first_cnode = ComponentNode.objects.filter(
            type="SOURCE", parent=None, purl=root_container.purl
        ).first()
        if first_cnode:
            if first_cnode.get_descendants().filter(type="SOURCE").exists():
                sb = root_container.software_build
                current_slow_save_taxonony.delay(sb.build_id, sb.build_type)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_remove_componentnode_core_cn_lft_tree_idx"),
    ]

    operations = [migrations.RunPython(save_container_taxonomy)]
