# Generated by Django 3.2.20 on 2023-11-27 05:50

from django.db import migrations
from django.db.models import Value

from corgi.core.models import Component


def copy_srpm_license_data_to_binary_rpms(apps, schema_editor) -> None:
    for scanned_srpm in (
        Component.objects.filter(type=Component.Type.RPM, arch="src")
        .exclude(license_concluded_raw="", copyright_text="")
        .iterator()
    ):
        scanned_srpm.provides.filter(type=Component.Type.RPM, nvr=scanned_srpm.nvr).update(
            copyright_text=Value(scanned_srpm.copyright_text),
            license_concluded_raw=Value(scanned_srpm.license_concluded_raw),
            license_declared_raw=Value(scanned_srpm.license_declared_raw),
            openlcs_scan_url=Value(scanned_srpm.openlcs_scan_url),
            openlcs_scan_version=Value(scanned_srpm.openlcs_scan_version),
        )


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("core", "0108_save_container_taxonomy"),
    ]

    operations = [
        migrations.RunPython(copy_srpm_license_data_to_binary_rpms),
    ]
