# Generated by Django 3.2.20 on 2023-12-04 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_add_product_node_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productstream",
            name="cpes_from_brew_tags",
        ),
    ]
