# Generated by Django 3.2.20 on 2023-12-11 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_change_stream_cpes_from_brew_tags_from_attr_to_property"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productstream",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productstreams",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="productstream",
            name="productversions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productstreams",
                to="core.productversion",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariants",
                to="core.product",
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="productversions",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productvariants",
                to="core.productversion",
            ),
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="productstreams",
        ),
        migrations.AddField(
            model_name="productvariant",
            name="productstreams",
            field=models.ManyToManyField(related_name="productvariants", to="core.ProductStream"),
        ),
        migrations.AlterField(
            model_name="productversion",
            name="products",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productversions",
                to="core.product",
            ),
        ),
    ]
