# Generated by Django 3.2.22 on 2023-12-15 05:41

from django.db import migrations

from corgi.core.constants import GET_LATEST_COMPONENT_STOREDPROC_SQL


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_save_variant_components"),
    ]

    operations = [
        migrations.RunSQL(GET_LATEST_COMPONENT_STOREDPROC_SQL),
    ]
