# Generated by Django 3.2.22 on 2024-01-16 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_remove_active_streams_filter_from_latest_variants_cursor"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="et_product",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="et_product_version",
            field=models.CharField(default="", max_length=1000),
        ),
    ]
