# Generated by Django 3.2.22 on 2024-02-12 05:14

import logging

from django.db import migrations
from django.db.models.fields.json import KeyTextTransform

from corgi.core.models import SoftwareBuild

logger = logging.getLogger(__name__)


def fix_softwarebuild_names(apps, schema_editor) -> None:
    for names in (
        SoftwareBuild.objects.filter(build_type="BREW")
        .exclude(meta_attr__name="")
        .values("name", "meta_attr__name")
        .distinct()
    ):
        # Do this comparison in Python to avoid type casting in database query
        if names["name"] != names["meta_attr__name"]:
            logger.info(
                f"Updating SoftwareBuild name {names['name']} to {names['meta_attr__name']}"
            )
            SoftwareBuild.objects.filter(build_type="BREW", name=names["name"]).update(
                name=KeyTextTransform("name", "meta_attr")
            )


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("core", "0116_accept_set_of_ofuris_to_get_latest_components"),
    ]

    operations = [
        migrations.RunPython(fix_softwarebuild_names),
    ]
