# Generated by Django 3.2.22 on 2024-03-21 01:17
import logging

from django.db import migrations

logger = logging.getLogger(__name__)


def update_container_related_urls(apps, schema_editor) -> None:
    Component = apps.get_model("core", "Component")
    for container in Component.objects.filter(
        type="OCI", namespace="REDHAT", related_url="registry.redhat.io"
    ).iterator():
        if "repository_url" in container.meta_attr:
            logger.info(
                f"Setting related_url for {container.nevra} to "
                f"{container.meta_attr['repository_url']}"
            )
            container.related_url = container.meta_attr["repository_url"]
        else:
            logger.info(f"Clearing {container.nevra} related_url")
            container.related_url = ""
        container.save()


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ("core", "0118_update_container_nvrs"),
    ]

    operations = [
        migrations.RunPython(update_container_related_urls),
    ]
